// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: internal/protocol/pb/rfmp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Msg
	//	*Frame_Frag
	//	*Frame_Svec
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_internal_protocol_pb_rfmp_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetMsg() *Msg {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *Frame) GetFrag() *Frag {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Frag); ok {
			return x.Frag
		}
	}
	return nil
}

func (x *Frame) GetSvec() *Svec {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Svec); ok {
			return x.Svec
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Msg struct {
	Msg *Msg `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type Frame_Frag struct {
	Frag *Frag `protobuf:"bytes,2,opt,name=frag,proto3,oneof"`
}

type Frame_Svec struct {
	Svec *Svec `protobuf:"bytes,3,opt,name=svec,proto3,oneof"`
}

func (*Frame_Msg) isFrame_Payload() {}

func (*Frame_Frag) isFrame_Payload() {}

func (*Frame_Svec) isFrame_Payload() {}

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromNode      string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	Timestamp     uint32                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	ReplyTo       []byte                 `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Author        string                 `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_internal_protocol_pb_rfmp_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Msg) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *Msg) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Msg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Msg) GetReplyTo() []byte {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *Msg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Msg) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Msg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type Frag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Idx           uint32                 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frag) Reset() {
	*x = Frag{}
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frag) ProtoMessage() {}

func (x *Frag) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frag.ProtoReflect.Descriptor instead.
func (*Frag) Descriptor() ([]byte, []int) {
	return file_internal_protocol_pb_rfmp_proto_rawDescGZIP(), []int{2}
}

func (x *Frag) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Frag) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Frag) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Frag) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Svec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	Vector        map[string]uint32      `protobuf:"bytes,2,rep,name=vector,proto3" json:"vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Svec) Reset() {
	*x = Svec{}
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Svec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Svec) ProtoMessage() {}

func (x *Svec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_pb_rfmp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Svec.ProtoReflect.Descriptor instead.
func (*Svec) Descriptor() ([]byte, []int) {
	return file_internal_protocol_pb_rfmp_proto_rawDescGZIP(), []int{3}
}

func (x *Svec) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *Svec) GetVector() map[string]uint32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_internal_protocol_pb_rfmp_proto protoreflect.FileDescriptor

const file_internal_protocol_pb_rfmp_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/pb/rfmp.proto\x12\x04rfmp\"u\n" +
	"\x05Frame\x12\x1d\n" +
	"\x03msg\x18\x01 \x01(\v2\t.rfmp.MsgH\x00R\x03msg\x12 \n" +
	"\x04frag\x18\x02 \x01(\v2\n" +
	".rfmp.FragH\x00R\x04frag\x12 \n" +
	"\x04svec\x18\x03 \x01(\v2\n" +
	".rfmp.SvecH\x00R\x04svecB\t\n" +
	"\apayload\"\xab\x01\n" +
	"\x03Msg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\rR\ttimestamp\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\fR\areplyTo\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x10\n" +
	"\x03seq\x18\a \x01(\rR\x03seq\"Y\n" +
	"\x04Frag\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\fR\x05msgId\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\rR\x03idx\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x8e\x01\n" +
	"\x04Svec\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12.\n" +
	"\x06vector\x18\x02 \x03(\v2\x16.rfmp.Svec.VectorEntryR\x06vector\x1a9\n" +
	"\vVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01B2Z0github.com/dprostko/rfmp-go/internal/protocol/pbb\x06proto3"

var (
	file_internal_protocol_pb_rfmp_proto_rawDescOnce sync.Once
	file_internal_protocol_pb_rfmp_proto_rawDescData []byte
)

func file_internal_protocol_pb_rfmp_proto_rawDescGZIP() []byte {
	file_internal_protocol_pb_rfmp_proto_rawDescOnce.Do(func() {
		file_internal_protocol_pb_rfmp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_pb_rfmp_proto_rawDesc), len(file_internal_protocol_pb_rfmp_proto_rawDesc)))
	})
	return file_internal_protocol_pb_rfmp_proto_rawDescData
}

var file_internal_protocol_pb_rfmp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protocol_pb_rfmp_proto_goTypes = []any{
	(*Frame)(nil), // 0: rfmp.Frame
	(*Msg)(nil),   // 1: rfmp.Msg
	(*Frag)(nil),  // 2: rfmp.Frag
	(*Svec)(nil),  // 3: rfmp.Svec
	nil,           // 4: rfmp.Svec.VectorEntry
}
var file_internal_protocol_pb_rfmp_proto_depIdxs = []int32{
	1, // 0: rfmp.Frame.msg:type_name -> rfmp.Msg
	2, // 1: rfmp.Frame.frag:type_name -> rfmp.Frag
	3, // 2: rfmp.Frame.svec:type_name -> rfmp.Svec
	4, // 3: rfmp.Svec.vector:type_name -> rfmp.Svec.VectorEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_protocol_pb_rfmp_proto_init() }
func file_internal_protocol_pb_rfmp_proto_init() {
	if File_internal_protocol_pb_rfmp_proto != nil {
		return
	}
	file_internal_protocol_pb_rfmp_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Msg)(nil),
		(*Frame_Frag)(nil),
		(*Frame_Svec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_pb_rfmp_proto_rawDesc), len(file_internal_protocol_pb_rfmp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_pb_rfmp_proto_goTypes,
		DependencyIndexes: file_internal_protocol_pb_rfmp_proto_depIdxs,
		MessageInfos:      file_internal_protocol_pb_rfmp_proto_msgTypes,
	}.Build()
	File_internal_protocol_pb_rfmp_proto = out.File
	file_internal_protocol_pb_rfmp_proto_goTypes = nil
	file_internal_protocol_pb_rfmp_proto_depIdxs = nil
}
