#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        systemctl stop rfmp-display.service 2>/dev/null || true
        systemctl stop rfmpd.service 2>/dev/null || true
        systemctl stop 'direwolf@*' 2>/dev/null || true
        systemctl disable rfmp-display.service 2>/dev/null || true
        systemctl disable rfmpd.service 2>/dev/null || true
        ;;
esac
